# fly.toml app configuration file generated for marinehq on 2023-10-15T20:00:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marinehq"
primary_region = "lhr"